version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: fruitgame-postgres
    environment:
      POSTGRES_DB: fruitgame
      POSTGRES_USER: fruitgame_user
      POSTGRES_PASSWORD: fruitgame_password
    ports:
      - "5432:5432"
    volumes:
      - fruitgame_pgdata:/var/lib/postgresql/data

volumes:
  fruitgame_pgdata:
